setblock ~ ~2 ~ light_block 15
setblock ~ ~-1 ~ bedrock
setblock ~ ~-1 ~1 bedrock
setblock ~ ~-1 ~-1 bedrock
setblock ~1 ~-1 ~ bedrock
setblock ~-1 ~-1 ~ bedrock
setblock ~ ~ ~2 bedrock
setblock ~ ~ ~-2 bedrock
setblock ~2 ~ ~ bedrock
setblock ~-2 ~ ~ bedrock
setblock ~1 ~ ~1 bedrock
setblock ~1 ~ ~-1 bedrock
setblock ~-1 ~ ~1 bedrock
setblock ~-1 ~ ~-1 bedrock	
setblock ~ ~1 ~3 bedrock
setblock ~ ~1 ~-3 bedrock
setblock ~3 ~1 ~ bedrock
setblock ~-3 ~1 ~ bedrock
setblock ~ ~2 ~3 bedrock
setblock ~ ~2 ~-3 bedrock
setblock ~3 ~2 ~ bedrock
setblock ~-3 ~2 ~ bedrock
setblock ~ ~3 ~3 bedrock
setblock ~ ~3 ~-3 bedrock
setblock ~3 ~3 ~ bedrock
setblock ~-3 ~3 ~ bedrock
setblock ~1 ~3 ~-2 bedrock
setblock ~-1 ~3 ~-2 bedrock
setblock ~1 ~3 ~2 bedrock
setblock ~-1 ~3 ~2 bedrock
setblock ~1 ~2 ~-3 bedrock
setblock ~3 ~2 ~1 bedrock
setblock ~-3 ~2 ~1 bedrock
setblock ~2 ~3 ~1 bedrock
setblock ~-2 ~3 ~1 bedrock
setblock ~-1 ~2 ~3 bedrock
setblock ~-1 ~2 ~-3 bedrock
setblock ~3 ~2 ~-1 bedrock
setblock ~-3 ~2 ~-1 bedrock
setblock ~-1 ~3 ~2 bedrock
setblock ~-1 ~3 ~-2 bedrock
setblock ~2 ~3 ~-1 bedrock
setblock ~-2 ~3 ~-1 bedrock
setblock ~2 ~1 ~1 bedrock
setblock ~2 ~1 ~-1 bedrock
setblock ~-2 ~1 ~1 bedrock
setblock ~-2 ~1 ~-1 bedrock
setblock ~1 ~1 ~2 bedrock
setblock ~1 ~1 ~-2 bedrock
setblock ~-1 ~1 ~2 bedrock
setblock ~-1 ~1 ~-2 bedrock
setblock ~2 ~2 ~-2 bedrock
setblock ~-2 ~2 ~-2 bedrock
setblock ~1 ~2 ~3 bedrock
setblock ~-2 ~2 ~2 bedrock
setblock ~2 ~4 ~ bedrock
setblock ~-2 ~4 ~ bedrock
setblock ~ ~4 ~2 bedrock
setblock ~ ~4 ~-2 bedrock
setblock ~2 ~2 ~2 bedrock
setblock ~-1 ~4 ~1 bedrock
setblock ~-1 ~4 ~-1 bedrock
setblock ~1 ~4 ~1 bedrock
setblock ~1 ~4 ~-1 bedrock
setblock ~ ~5 ~ bedrock
setblock ~ ~5 ~1 bedrock
setblock ~ ~5 ~-1 bedrock
setblock ~1 ~5 ~ bedrock
setblock ~-1 ~5 ~ bedrock
tellraw @s {"rawtext":[{"text":"§4Traped!"}]}